language: csharp
solution: libwarcraft.sln
before_install:
    - sudo add-apt-repository -y ppa:jarl-gullberg/blizzard-dev-tools
    - sudo apt-get update -q
    - sudo apt-get install -y dotnetzip-cli*
